### ISSUE TITLE
Error with rar file

### ISSUE THREAD

**Issue by rcgary** [gyh1621/GetSubtitles#1]
Thanks for the great work!
I found when searching subtitles with rar file, it always getting this error:
```
    info: Failed the read enough data.
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/main.py", line 484, in start
    sub_data_bytes, info_dict, self.single
  File "/usr/local/lib/python3.6/site-packages/main.py", line 397, in extract_subtitle
    sub.write(file_handler.read(sub_name))
  File "/usr/local/lib/python3.6/site-packages/rarfile.py", line 772, in read
    return f.read()
  File "/usr/local/lib/python3.6/site-packages/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
rarfile.BadRarFile: Failed the read enough data
```

**Comment by gyh1621** [comment]
具体是在搜索哪个字幕的时候遇到的呢，因为我下了很多rar都可以的

2017年11月12日 +0800 PM1:22 Chao Ruan <notifications@github.com>，写道：

**Comment by gyh1621** [comment]
can you give more details, like searching which episode or movie, choosing which subtitle to download
