### ISSUE TITLE
zimuku下载失败

### ISSUE THREAD

**Issue by fengyuyuju** [gyh1621/GetSubtitles#11]
├ Peter.Rabbit.2018.1080p.BluRay.H264.AAC-RARBG.mp4
├ /home/zabyss/DLTarget/Peter.Rabbit.2018.1080p.BluRay.H264.AAC-RARBG
├
├ error:No connection adapters were found for 'http:http://www.subku.net/dld/103128.html'.

===============================FAILED LIST===============================

 1. name: Peter.Rabbit.2018.1080p.BluRay.H264.AAC-RARBG.mp4
    path: /home/zabyss/DLTarget/Peter.Rabbit.2018.1080p.BluRay.H264.AAC-RARBG
    info: No connection adapters were found for 'http:http://www.subku.net/dld/103128.html'.
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/main.py", line 438, in start
    downloader.get_subtitles(tuple(keywords))
  File "/usr/local/lib/python3.6/site-packages/zimuku.py", line 153, in get_subtitles
    r = s.get(download_link, timeout=60)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 570, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 644, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'http:http://www.subku.net/dld/103128.html'

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
我这里[字幕库](http://www.zimuku.cn/)打不开，估计是挂了，所以这个错误也复现不了，通过 pip 升级一下吧，新版本会跳过 zimuku 下载器的
