### ISSUE TITLE
显示报错

### ISSUE THREAD

**Issue by SelfEnough** [gyh1621/GetSubtitles#12]
1. name: Paddington.2(2017).mkv
    path: X:\影视\电影\(8.2分)-帕丁顿熊2(2017)
    info: No connection adapters were found for 'http:http://www.subku.net/dld/103695.html'.
    TRACE_BACK: Traceback (most recent call last):
  File "C:\Python\Scripts\main.py", line 438, in start
    downloader.get_subtitles(tuple(keywords))
  File "C:\Python\Scripts\zimuku.py", line 153, in get_subtitles
    r = s.get(download_link, timeout=60)
  File "c:\python\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "c:\python\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\python\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'http:http://www.subku.net/dld/103695.html'

问题应该出在两个http：但是我不知道怎么改。麻烦大大指教

**Comment by gyh1621** [comment]
用 -d 指定下载器吧，zimuku这个网站现在大部分时间连不上，连上了看来网页结构也变了，我下次还是直接去掉zimuku下载器好了
