### ISSUE TITLE
字幕下载失败

### ISSUE THREAD

**Issue by zscorpio** [gyh1621/GetSubtitles#15]
```
├ I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE.mkv
├ /Volumes/video/I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE
├
├ Get '[ZMZ]I.Robot.2004.OPEN.MATTE.720p.BluRay.DTS.x264-PublicHD'...  100.00%
├ error:'utf8' codec can't decode byte 0xbc in position 108: invalid start byte.

===============================FAILED LIST===============================

 1. name: I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE.mkv
    path: /Volumes/video/I.Robot.2004.1080p.Bluray.x264.DTS-DEFiNiTE
    info: 'utf8' codec can't decode byte 0xbc in position 108: invalid start byte.
    TRACE_BACK: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/main.py", line 505, in start
    sub_data_bytes, info_dict, self.single
  File "/Library/Python/2.7/site-packages/main.py", line 401, in extract_subtitle
    + os.path.splitext(sub_name.decode('utf8'))[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbc in position 108: invalid start byte


total: 1  success: 0  fail: 1
```

**Comment by gyh1621** [comment]
已更新
