### ISSUE TITLE
有关subhd获取字幕失败

### ISSUE THREAD

**Issue by sokouu** [gyh1621/GetSubtitles#18]
Hi, 一直正常使用，十分感谢！最近出现个bug，下载subhd字幕失败，zimuzu的没问题，有空帮忙看一下是哪儿出问题了。

xxx:~ xxx$ getsub '/Users/xxx/Downloads/Along.with.the.Gods_The.Last.49.Days.2017.1080p.FHDRip.H264.AAC-NonDRM.mp4' --debug

├  Along.with.the.Gods_The.Last.49.Days.2017.1080p.FHDRip.H264.AAC-NonDRM.mp4
├  /Users/shaogongyu/Downloads
├
├  error:Expecting value: line 2 column 1 (char 1).

===============================FAILED LIST===============================

 1. name: Along.with.the.Gods_The.Last.49.Days.2017.1080p.FHDRip.H264.AAC-NonDRM.mp4
    path: /Users/xxx/Downloads
    info: Expecting value: line 2 column 1 (char 1).
    TRACE_BACK: Traceback (most recent call last):
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/main.py", line 590, in start
    sub_choice, link, info_dict)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/main.py", line 484, in process_archive
    download_file(sub_choice, link)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/subhd.py", line 120, in download_file
    if json.loads(content)['success'] is False:
  File "/Users/xxx/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
subhd最近下载要滑动验证了，之前是短时间下载多条才会出现滑动验证，如果一直都是这样，那就只能取消subhd下载器了。可能后面会重新使用zimuku的下载器。
