### ISSUE TITLE
KeyError: 'content-disposition'

### ISSUE THREAD

**Issue by minjin** [gyh1621/GetSubtitles#20]
` 1. name: After.the.Storm.2016.1080p.BluRay.x264-WiKi.mkv
    path: /root/nfs/Movies
    info: 'content-disposition'.
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/getsub/main.py", line 615, in start
    sub_choice, link, session, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/getsub/main.py", line 514, in process_archive
    sub_choice, link, session=session
  File "/usr/local/lib/python2.7/dist-packages/getsub/zimuku.py", line 192, in download_file
    filename = response.headers['Content-Disposition']
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'`

这个报错会偶发，视频文件名是匹配的，通过 -q 是可以正常获得搜索结果，但是依然会提示这个错误...

通过尝试修改文件名依然会引发错误...

**Comment by gyh1621** [comment]
已确认 会尽快解决

**Comment by gyh1621** [comment]
不好意思过了这么久才去解决，我重新试了几次，错误已经不能复现了。“偶发”可能是当时网络连接问题？

**Comment by minjin** [comment]
应该是我谢谢你提供这么好的工具，刚刚又试了一下，已经没有问题了。
