### ISSUE TITLE
MissingSchema(error) MissingSchema: Invalid URL 

### ISSUE THREAD

**Issue by JingenChen** [gyh1621/GetSubtitles#22]
root@DietPi:/mnt/samba/Video/Movies# getsub ./Perfect.Strangers.2017.1080p.BluRay.x264-USURY\[rarbg\]/ -d zimuku --plex --debug

├  perfect.strangers.2017.1080p.bluray.x264-usury.mkv
├  ./Perfect.Strangers.2017.1080p.BluRay.x264-USURY[rarbg]/
├ 
├  error:Invalid URL '/download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1': No schema supplied. Perhaps you meant http:///download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1?. 

===============================FAILED LIST===============================

 1. name: perfect.strangers.2017.1080p.bluray.x264-usury.mkv
    path: ./Perfect.Strangers.2017.1080p.BluRay.x264-USURY[rarbg]/
    info: Invalid URL '/download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1': No schema supplied. Perhaps you meant http:///download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1?. 
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/getsub/main.py", line 615, in start
    sub_choice, link, session, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/getsub/main.py", line 514, in process_archive
    sub_choice, link, session=session
  File "/usr/local/lib/python2.7/dist-packages/getsub/zimuku.py", line 196, in download_file
    with closing(session.get(download_link, stream=True)) as response:
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '/download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1': No schema supplied. Perhaps you meant http:///download/NTIzODd8NDA1ZTA5NDZiY2U3ODIzZjBkMDI0OTI1fDE1NDY4Mzk5NjZ8YmU1MTNhYTJ8cmVtb3Rl/svr/dx1?

total: 1  success: 0  fail: 1

**Comment by ihainan** [comment]
Same issue here.

**Comment by spielenWang** [comment]
修改zimuku.py file 
download_link = download_link.attrs['href']  代替为 download_link = self.site_url + download_link.attrs['href']

**Comment by gyh1621** [comment]
最新版本已修复
