### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by panyuz** [gyh1621/GetSubtitles#23]
anaconda 里面装的

 name: Marvels.Agents.of.S.H.I.E.L.D.S01E02.1080p.WEB-DL.DD5.1.H264-PublicHD-Obfuscated.mkv
    path: D:\tv\Marvel's Agents of S.H.I.E.L.D\Season 1
    info: unknown error. try again.
    TRACE_BACK: Traceback (most recent call last):
  File "c:\users\smart\anaconda3\lib\site-packages\getsub\main.py", line 584, in start
    downloader.get_subtitles(tuple(keywords))
  File "c:\users\smart\anaconda3\lib\site-packages\getsub\zimuzu.py", line 46, in get_subtitles
    tab_text = bs_obj.find('div', {'class': 'article-tab'}).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by jzz3933** [comment]
我也遇到了这个问题，指定用zimuku做下载器后，也会报错

├  Sex.Education.S01E01.Episode.1.1080p.NF.WEB-DL.DDP5.1.x264-MZABI.mkv
├  E:\download\Sex.Education.S01.1080p.NF.WEB-DL.DDP5.1.x264-MZABI
├
├  error:Invalid URL '/download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5YmRmZmU3ZnwxNTUxNzkwMjIyfDhjZjU5YmI4fHJlbW90ZQ%3D%3D/sv
r/dx1': No schema supplied. Perhaps you meant http:///download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5YmRmZmU3ZnwxNTUxNzkwMjIyf
DhjZjU5YmI4fHJlbW90ZQ%3D%3D/svr/dx1?.

===============================FAILED LIST===============================

 1. name: Sex.Education.S01E01.Episode.1.1080p.NF.WEB-DL.DDP5.1.x264-MZABI.mkv
    path: E:\download\Sex.Education.S01.1080p.NF.WEB-DL.DDP5.1.x264-MZABI
    info: Invalid URL '/download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5YmRmZmU3ZnwxNTUxNzkwMjIyfDhjZjU5YmI4fHJlbW90ZQ%3D%3D/sv
r/dx1': No schema supplied. Perhaps you meant http:///download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5YmRmZmU3ZnwxNTUxNzkwMjIyf
DhjZjU5YmI4fHJlbW90ZQ%3D%3D/svr/dx1?.
    TRACE_BACK: Traceback (most recent call last):
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\getsub-1.6.8.2-py3.6.egg\getsub\main.py", line 615, in start
    sub_choice, link, session, info_dict)
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\getsub-1.6.8.2-py3.6.egg\getsub\main.py", line 514, in process_archive
    sub_choice, link, session=session
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\getsub-1.6.8.2-py3.6.egg\getsub\zimuku.py", line 196, in download_file
    with closing(session.get(download_link, stream=True)) as response:
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\requests\models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Jzz\Anaconda3\lib\site-packages\requests\models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5YmRmZmU3ZnwxNTUxNzkwMjIyfDhjZj
U5YmI4fHJlbW90ZQ%3D%3D/svr/dx1': No schema supplied. Perhaps you meant http:///download/MTEzMzE5fDdhY2M2YjhhNGZiM2VlY2M5
YmRmZmU3ZnwxNTUxNzkwMjIyfDhjZjU5YmI4fHJlbW90ZQ%3D%3D/svr/dx1?

**Comment by gyh1621** [comment]
@panyuz @jzz3933 最新版本已修复。
