### ISSUE TITLE
报错为啥？

### ISSUE THREAD

**Issue by crazynet999** [gyh1621/GetSubtitles#27]
1. name: Exodus-Gods.and.Kings.2014.Bluray.1080p.DTS-HD-7.1.x264-Grym.mkv
    path: Y:\rclonegdrive\出埃及记Exodus-Gods.and.Kings.2014.Bluray.1080p.DTS-HD-7.1.x264-Grym
    info: Expecting value: line 1 column 1 (char 0).
    TRACE_BACK: Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\getsub\main.py", line 623, in start
    sub_choice, link, session, info_dict)
  File "c:\python\python37\lib\site-packages\getsub\main.py", line 513, in process_archive
    download_file(sub_choice, link)
  File "c:\python\python37\lib\site-packages\getsub\subhd.py", line 127, in download_file
    if json.loads(content)['success'] is False:
  File "c:\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gyh1621** [comment]
已更新
