### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by probestar** [gyh1621/GetSubtitles#30]
➜  ~ getsub 'Airwolf_-_1x11_-_Mind_Of_The_Machine.(DVD).uDF.avi' --debug  

├  Airwolf_-_1x11_-_Mind_Of_The_Machine.(DVD).uDF.avi
├  /Users/probestar
├ 
├  error:Expecting value: line 1 column 1 (char 0). 

===============================FAILED LIST===============================

 1. name: Airwolf_-_1x11_-_Mind_Of_The_Machine.(DVD).uDF.avi
    path: /Users/probestar
    info: Expecting value: line 1 column 1 (char 0). 
    TRACE_BACK: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/getsub/main.py", line 623, in start
    sub_choice, link, session, info_dict)
  File "/usr/local/lib/python3.7/site-packages/getsub/main.py", line 513, in process_archive
    download_file(sub_choice, link)
  File "/usr/local/lib/python3.7/site-packages/getsub/subhd.py", line 127, in download_file
    if json.loads(content)['success'] is False:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
已更新，麻烦升级到1.6.8.7
