### ISSUE TITLE
ImportError: cannot import name 'HTMLParseError'

### ISSUE THREAD

**Issue by Endless-Run** [gyh1621/GetSubtitles#31]
当运行`getsub`时, 会出现下面的报错:
> Traceback (most recent call last):
  File "/home/xxx/.local/bin/getsub", line 6, in <module>
    from getsub.main import main
  File "/home/xxx/.local/lib/python3.5/site-packages/getsub/main.py", line 20, in <module>
    from getsub.subhd import SubHDDownloader
  File "/home/xxx/.local/lib/python3.5/site-packages/getsub/subhd.py", line 12, in <module>
    from bs4 import BeautifulSoup
  File "/home/xxx/.local/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/xxx/.local/lib/python3.5/site-packages/bs4/builder/__init__.py", line 308, in <module>
    from . import _htmlparser
  File "/home/xxx/.local/lib/python3.5/site-packages/bs4/builder/_htmlparser.py", line 7, in <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'

`Python`版本: 3.5.2

**Comment by gyh1621** [comment]
升级一下 bs4：`pip install --upgrade bs4`

**Comment by gyh1621** [comment]
升级到新版本试试：`pip install --upgrade getsub`，最新的版本注意为1.6.8.9

**Comment by Endless-Run** [comment]
升级到最新版本之后问题得到解决，出现问题的版本为1.6.8.7
