### ISSUE TITLE
无法下载，不知道哪里错了 

### ISSUE THREAD

**Issue by tanryliu** [gyh1621/GetSubtitles#63]
getsub Z:\movie\Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino\Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv --debug

- Video: Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv
- Video Path: Z:\movie\Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino
- Subtitles Store Path: Z:\movie\Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino

ERROR:An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "c:\python38\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "c:\python38\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "c:\python38\lib\site-packages\guessit\rules\properties\episodes.py", line 168, in episodes
    rebulk.chain(
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "c:\python38\lib\site-packages\rebulk\pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "c:\python38\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================.  failed to guess one subtitle,use '-q' to try query mode.

===============================FAILED LIST===============================

 1. name: Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv
    path: Z:\movie\Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino
    info: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "c:\python38\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "c:\python38\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "c:\python38\lib\site-packages\guessit\rules\properties\episodes.py", line 168, in episodes
    rebulk.chain(
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "c:\python38\lib\site-packages\rebulk\pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "c:\python38\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================.  failed to guess one subtitle,use '-q' to try query mode.
    TRACE_BACK: Traceback (most recent call last):
  File "c:\python38\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "c:\python38\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "c:\python38\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "c:\python38\lib\site-packages\guessit\rules\properties\episodes.py", line 168, in episodes
    rebulk.chain(
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "c:\python38\lib\site-packages\rebulk\pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "c:\python38\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\getsub\main.py", line 170, in start
    error, extract_sub_names = self.process_video(one_video, video_info)
  File "c:\python38\lib\site-packages\getsub\main.py", line 117, in process_video
    sub_dict = self.get_search_results(video_name)
  File "c:\python38\lib\site-packages\getsub\main.py", line 64, in get_search_results
    result = downloader.get_subtitles(video_name, sub_num=self.sub_num)
  File "c:\python38\lib\site-packages\getsub\downloader\subhd.py", line 31, in get_subtitles
    keywords, info_dict = Downloader.get_keywords(video_name)
  File "c:\python38\lib\site-packages\getsub\downloader\downloader.py", line 36, in get_keywords
    info_dict = guessit(video_name)
  File "c:\python38\lib\site-packages\guessit\api.py", line 71, in guessit
    return default_api.guessit(string, options)
  File "c:\python38\lib\site-packages\guessit\api.py", line 222, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Spies.in.Disguise.2019.2160p.UHD.BluRay.x265-WhiteRhino.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\guessit\api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "c:\python38\lib\site-packages\guessit\api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "c:\python38\lib\site-packages\guessit\rules\__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "c:\python38\lib\site-packages\guessit\rules\properties\episodes.py", line 168, in episodes
    rebulk.chain(
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "c:\python38\lib\site-packages\rebulk\builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "c:\python38\lib\site-packages\rebulk\pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "c:\python38\lib\site-packages\rebulk\loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "c:\python38\lib\site-packages\regex\regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'formatter'
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

total: 1  success: 0  fail: 1

**Comment by gyh1621** [comment]
这个我也碰到过，我好像是重装了`guessit`或者换了 python 版本。
