### ISSUE TITLE
Random ValueError: unused keyword argument 'xxxxxx'

### ISSUE THREAD

**Issue by PetrusZ** [gyh1621/GetSubtitles#67]
For instances:
```
ERROR:An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Ford.v.Ferrari.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/rules/properties/episodes.py", line 175, in episodes
    build_or_pattern(episode_markers + disc_markers, name='episodeMarker') + r'@?(?P<episode>\d+)')\
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib64/python3.6/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib64/python3.6/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'
--------------------------------------------------------------------
```

But if you run getsub again, it will show another error:

```
Searching SUBHD...^MERROR:An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.1.0
string=Ford.v.Ferrari.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR.mkv
options={}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/api.py", line 192, in guessit
    config = self.configure(options, sanitize_options=False)
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/home/petrus/.local/lib64/python3.6/site-packages/guessit/rules/properties/episodes.py", line 175, in episodes
    build_or_pattern(episode_markers + disc_markers, name='episodeMarker') + r'@?(?P<episode>\d+)')\
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/home/petrus/.local/lib64/python3.6/site-packages/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib64/python3.6/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib64/python3.6/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'abbreviations'
--------------------------------------------------------------------
```

Python version:Python 3.6.10

**Comment by gyh1621** [comment]
见 #63，应该是 guessit 的问题
