### ISSUE TITLE
pip的版本需要更新

### ISSUE THREAD

**Issue by NormanBB** [gyh1621/GetSubtitles#68]
pip目前最新版本1.7.6，Released: Mar 13, 2020。

你3月15日的commit移除了subhd，pip版本未同步。

错误信息`error:'NoneType' object is not subscriptable`

同时建议完善 pip Project description

**Comment by NormanBB** [comment]
在使用脚本过程中，运行 `getsub --debug The.Morning.Show.S01`

发生以下错误。

 ```
PS F:\The.Morning.Show.S01.720p.ATVP.WEB-DL.DDP5.1.Atmos.x264-MZABI[rartv]> getsub --debug The.Morning.Show.S01

- Video: The.Morning.Show.S01
- Video Path: The.Morning.Show.S01
- Subtitles Store Path: F:\The.Morning.Show.S01.720p.ATVP.WEB-DL.DDP5.1.Atmos.x264-MZABI[rartv]

ERROR:'NoneType' object has no attribute 'group'.  failed to guess one subtitle,use '-q' to try query mode.

===============================FAILED LIST===============================

 1. name: The.Morning.Show.S01
    path: The.Morning.Show.S01
    info: 'NoneType' object has no attribute 'group'.  failed to guess one subtitle,use '-q' to try query mode.
    TRACE_BACK: Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python38-32\lib\site-packages\getsub\main.py", line 170, in start
    error, extract_sub_names = self.process_video(one_video, video_info)
  File "c:\users\lenovo\appdata\local\programs\python\python38-32\lib\site-packages\getsub\main.py", line 117, in process_video
    sub_dict = self.get_search_results(video_name)
  File "c:\users\lenovo\appdata\local\programs\python\python38-32\lib\site-packages\getsub\main.py", line 64, in get_search_results
    result = downloader.get_subtitles(video_name, sub_num=self.sub_num)
  File "c:\users\lenovo\appdata\local\programs\python\python38-32\lib\site-packages\getsub\downloader\zimuku.py", line 159, in get_subtitles
    season_cn1 = re.search("第(.*)季", title).group(1).strip()
AttributeError: 'NoneType' object has no attribute 'group'


total: 1  success: 0  fail: 1
 ```
看了一下代码，应该是有字幕搜索结果的，但是re没有搜索到符合条件的结果。

**Comment by gyh1621** [comment]
这两天会推上去

**Comment by gyh1621** [comment]
已推，麻烦更新到 1.7.7

**Comment by NormanBB** [comment]
> 已推，麻烦更新到 1.7.7

**:)**
